#!/usr/bin/env bash
set -euo pipefail
ram=$(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')

echo 0 > /sys/module/zswap/parameters/enabled
modprobe zram

echo zstd > /sys/block/zram0/comp_algorithm
echo "$((ram * 2))" > /sys/block/zram0/disksize
echo "${ram}" > /sys/block/zram0/mem_limit
mkswap --label zram0 /dev/zram0
swapon --priority 255 /dev/zram0


cat /sys/class/zram-control/hot_add
echo zstd > /sys/block/zram1/comp_algorithm
echo "$((ram * 2))" > /sys/block/zram1/disksize
echo "$((ram * 85 / 100))" > /sys/block/zram1/mem_limit
mkfs.ext4 /dev/zram1
tune2fs -O "^has_journal" /dev/zram1


mount -t tmpfs -o size=0,nr_inodes=0 tmpfs /tmp
mount -t ext4 -o noatime,nodiratime,barrier=0 /dev/zram1 /tmp
chmod 1777 /tmp
